version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build: .
    # Прокидываем скомпилированный по стандартам Node.js файл обратно на ваш ПК и включаем PHP
    command: sh -c "cp /tmp/tailwind.css /var/www/html/public/includes/tailwind.css && php-fpm -d upload_max_filesize=2000M -d post_max_size=2000M"
    volumes:
      - ./:/var/www/html
