version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build: .
    # УВЕЛИЧИВАЕМ ЛИМИТЫ PHP ДО 2 ГИГАБАЙТ ПРЯМО ПРИ СТАРТЕ
    command: php-fpm -d upload_max_filesize=2000M -d post_max_size=2000M
    volumes:
      - ./:/var/www/html
