server {
    listen 80;
    server_name localhost;
    root /var/www/html/public;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Разрешаем Nginx напрямую отдавать стили из папки includes
    location /includes/ {
        alias /var/www/html/public/includes/;
        autoindex off;
    }

    # Разрешаем Nginx напрямую отдавать видеофайлы в плеер
    location /storage/videos/ {
        alias /var/www/html/storage/videos/;
        autoindex off;
    }

    location /storage/thumbnails/ {
        alias /var/www/html/storage/thumbnails/;
        autoindex off;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
